# Generated by Django 4.2.13 on 2024-07-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceCheckInApp', '0003_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
