# Generated by Django 4.2.13 on 2024-07-14 11:40

import FaceCheckInApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceCheckInApp', '0004_remove_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='photo1',
            field=models.ImageField(upload_to=FaceCheckInApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='photo2',
            field=models.ImageField(upload_to=FaceCheckInApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='photo3',
            field=models.ImageField(upload_to=FaceCheckInApp.models.user_directory_path),
        ),
    ]
